import { OrderDetail } from "@/app/(admin)/admin/type";
import { Order } from "./type";

export const orders: Order[] = [
  {
    id: "LG-00030",
    customer: "Aminu Ibrahim",
    phone: "+234 802 123 4567",
    from: "Tanke",
    to: "GRA",
    riderName: "Sodiq Bello",
    riderAvatar: "/avatars/sodiq.png",
    priority: "express",
    status: "in_transit",
    createdTime: "10:24 AM",
  },
  {
    id: "LG-00031",
    customer: "Funke Adebayo",
    phone: "+234 701 987 6543",
    from: "Fate",
    to: "Challenge",
    riderName: "Jamiu Kola",
    riderAvatar: "/avatars/jamiu.png",
    priority: "normal",
    status: "delivered",
    createdTime: "09:15 AM",
  },
  {
    id: "LG-00032",
    customer: "Blessing Okafor",
    phone: "+234 803 456 7890",
    from: "Sango",
    to: "Pipeline",
    riderName: "Ridwan Musa",
    riderAvatar: "/avatars/ridwan.png",
    priority: "normal",
    status: "pending",
    createdTime: "08:50 AM",
  },
  {
    id: "LG-00033",
    customer: "Chidi Eze",
    phone: "+234 805 234 1122",
    from: "Taiwo Road",
    to: "Oke Odo",
    riderName: "Azeez Kunle",
    riderAvatar: "/avatars/azeez.png",
    priority: "express",
    status: "assigned",
    createdTime: "08:30 AM",
  },
  {
    id: "LG-00034",
    customer: "Ngozi Umeh",
    phone: "+234 806 778 3344",
    from: "University Road",
    to: "Basin",
    riderName: "Sodiq Bello",
    riderAvatar: "/avatars/sodiq.png",
    priority: "normal",
    status: "picked_up",
    createdTime: "08:10 AM",
  },
];

const order: OrderDetail = {
  id: "LG-00030",
  status: "in_transit",
  createdTime: "Today, 09:00 AM",
  customerName: "Aminu Ibrahim",
  customerEmail: "aminu.i@example.com",
  customerPhone: "+234 802 123 4567",
  pickupAddress: "Shop 42, Tanke Shopping Mall, Tanke Road, Ilorin.",
  destinationAddress: "Block B, GRA Court, Off Taiwo Road, GRA, Ilorin.",
  deliveryNotes:
    "Handle with care - fragile electronics. Please call upon arrival at the gate.",
  timeline: [
    { label: "Order Created", time: "Today, 09:00 AM", state: "done" },
    { label: "Rider Assigned", time: "Today, 09:15 AM", state: "done" },
    { label: "Package Picked Up", time: "Today, 10:05 AM", state: "done" },
    { label: "Out for Delivery", time: "Today, 10:24 AM", state: "current" },
    { label: "Delivered", time: "Estimated in 15 mins", state: "upcoming" },
  ],
};
